# -*- coding: utf-8 -*-
"""data_split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsVxbzNxfNyJE4tBtOYzqX4chAzpHnQA
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/CSC8639_folder')

import numpy as np
from glob import glob
import pickle

ALL_IMAGES_DIR = glob(r"/content/drive/MyDrive/CSC8639_folder/all_data/img/*")
ALL_MASK_DIR = glob(r"/content/drive/MyDrive/CSC8639_folder/all_data/label/*")

for path in ALL_IMAGES_DIR:
    print(path)

print(len(ALL_IMAGES_DIR))
print(len(ALL_MASK_DIR))

# 20/20/60 train test unlabelled
np.random.shuffle(ALL_IMAGES_DIR)
train_val_img = ALL_IMAGES_DIR[:700]
test_img = ALL_IMAGES_DIR[700:1400]
unlabelled_img = ALL_IMAGES_DIR[1400:2700]
train_val_label = []
for i in train_val_img:
    train_val_label.append(i.replace("img", "label"))
test_label = []
for i in test_img:
    test_label.append(i.replace("img", "label"))
unlabelled_label = []
for i in unlabelled_img:
    unlabelled_label.append(i.replace("img", "label"))

pickle.dump(train_val_img, open('/content/drive/MyDrive/CSC8639_folder/process_data/train_val/image/train_val.data', 'wb'), -1)
pickle.dump(train_val_label, open('/content/drive/MyDrive/CSC8639_folder/process_data/train_val/label/train_val.mask', 'wb'), -1)
pickle.dump(test_img, open('/content/drive/MyDrive/CSC8639_folder/process_data/test/image/test.data', 'wb'), -1)
pickle.dump(test_label, open('/content/drive/MyDrive/CSC8639_folder/process_data/test/label/test.mask', 'wb'), -1)
pickle.dump(unlabelled_img, open('/content/drive/MyDrive/CSC8639_folder/process_data/unlabelled/image/unlabelled.data', 'wb'), -1)
pickle.dump(unlabelled_label, open('/content/drive/MyDrive/CSC8639_folder/process_data/unlabelled/label/unlabelled.mask', 'wb'), -1)